### ISSUE TITLE
Infografía - Lenguajes de programación

### ISSUE THREAD

**Issue by IsaHuerta23** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-IsaHuerta23#1]
Infografía - Lenguajes de programación 

[Infografía  - Lenguajes de programación.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-IsaHuerta23/files/8469665/Infografia.-.Lenguajes.de.programacion.pdf)

**Comment by AndreLuna6** [comment]
Calificación: 20/20


Partes de una infografía: 4
-Coherencia y pertenencia: 4
-Organización de
la información: 4
-Diseño y
composición de
la infografía: 4
-Creatividad: 4

**Comment by josealfredo79** [comment]
Bien hecho y revisado
